### ISSUE TITLE
Extra comma breaking Coldfusion

### ISSUE THREAD

**Issue by alorne** [inLeagueLLC/wkhtmltopdf#1]
On line 38 of ModuleConfig.cfc `pdfsecure = false,' the comma at the end of false is breaking it in ACF2021

**Comment by alorne** [comment]
Error text
`<html>
<body>


Invalid CFML construct found on line 39 at column 17.
--
ColdFusion was looking at the following text:}The CFML compiler was processing:A script statement beginning with settings on line 35, column 17.A script statement beginning with function on line 27, column 9.
 
The error occurred in /app/modules/wkhtmltopdf/ModuleConfig.cfc: line 39Called from /app/coldbox/system/core/util/Util.cfc: line 413Called from /app/coldbox/system/ioc/config/Mapping.cfc: line 521Called from /app/coldbox/system/ioc/config/Mapping.cfc: line 532Called from /app/coldbox/system/ioc/Injector.cfc: line 508Called from /app/coldbox/system/web/services/ModuleService.cfc: line 939Called from /app/coldbox/system/web/services/ModuleService.cfc: line 355Called from /app/coldbox/system/web/services/ModuleService.cfc: line 135Called from /app/coldbox/system/web/services/ModuleService.cfc: line 56Called from /app/coldbox/system/web/services/LoaderService.cfc: line 70Called from /app/coldbox/system/bootstrap.cfc: line 110Called from /app/Application.cfc: line 25
37 : 			pdfport			=	3000,				// http/s port for wkhtmltopdf service. default of 3000 is used by the wkhtmltopdf docker container 38 : 			pdfsecure		=	false,				// false = http, true = https 39 : 		}; 40 :  41 : 	}


</body>
</html>`

**Comment by DiscountDarcy** [comment]
Fixed and updated on Forgebox. Thanks!

**Comment by alorne** [comment]
Forgebox still has the extra comma

Cavan

**Comment by DiscountDarcy** [comment]
Forgebox download location / package is fixed!

**Comment by alorne** [comment]
Thanks! Can confirm the file is fixed. I have two more tickets coming.

Thanks

Cavan
