### ISSUE TITLE
url vs content check PDFService.cfc

### ISSUE THREAD

**Issue by alorne** [inLeagueLLC/wkhtmltopdf#2]
Getting the error `Invalid CFML construct found on line 32 at column 21.` in file PDFService.cfc. the issue seems to be with the elvis operator `( isURL ? "url" : "content" ) : arguments.content,`

**Comment by DiscountDarcy** [comment]
Fixes like these should be super easy.

I don't work with ACF anymore, so if you leave it to me to spin it up and test it, it'll happen but it'll be a while.

If you want to submit a merge request with a re-write of that line to not use the elvis operator, I'll accept it!

**Comment by alorne** [comment]
Ok, I'll do that

**Comment by alorne** [comment]
I submitted a pull request for this #3
